language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-interaction

script:
  - vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
  - vendor/bin/phpunit
